name: GOCDB Webserver Tests

on: [push]

services:
  mysql:
    image: mariadb:10
    ports: 13306:3306
    env:
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_ROOT_PASSWORD: root
    ports: 13306:3306 

jobs:
  linux:
    strategy: 
      # Don't cancel all the jobs if one fails.
      fail-fast: false 
      matrix:
        container:
        - 'centos:7'

    runs-on: ubuntu-latest
    container: ${{ matrix.container }}

    steps:
    # Checkout the codebase.
    - uses: actions/checkout@v2

    - name: Install EPEL Release # for things like composer
      run: yum -y install epel-release

    - name: Install httpd
      run: yum -y install httpd

    - name: Start MariaDB
      run: systemctl start mysql

    - name: Install GOCDB Requirements
      run: yum -y install php php-xml php-devel php-pear gcc composer

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install Dependencies
      run: composer install

    - name: Compile Doctrine Entities
      run: mkdir -p compiledEntities && vendor/bin/doctrine orm:generate-proxies compiledEntities/
      env: 
          COMPOSER_HOME: $GITHUB_WORKSPACE

